api/urls.py
from os import name
from django.urls import path, include
from . import views
from rest_framework.routers import DefaultRouter   # REST-Framework


app_name = 'api'


urlpatterns = [
# API view
    path('post/', views.PostApiView.as_view(), name='postCreateView'),
    path('post/contact/', views.PostContactApiView.as_view(), name='postContactCreateView'),
    path('post/contact2/', views.PostContactGetView.as_view(), name='postContactGetView'),
    path('post/contact/<pk>', views.PostContactDetailApiView.as_view(), name='postContactDetailView'),
    path('post/delete', views.PostDeleteApiView.as_view(), name='postDeleteView'),
    path('post/nocontact', views.PostContactFalse.as_view(), name='PostContactFalse'),
]

domru/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    path('api/', include('api.urls', namespace='api')),
    path('', include('main.urls', namespace='main')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,  document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,  document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .import views



app_name = 'main'



urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('post/<pk>', views.PostDetailView.as_view(), name="post_details"),
    # path('details/<slug:slug>', views.PostDetailsView.as_view(), name='post_details'),
    # path('update/<slug:slug>', views.PostUpdateView.as_view(), name='post_update'),
    # path('category/<slug:slug>', views.CategorySortView.as_view(), name='category_sort'),
    # path('addlike/', views.add_to_liked, name='add_to_liked'),
    # path('comment/', views.comment, name='comment'),


]

templates/index.html
{% extends 'wrapper.html' %}




{% block content %}

<div class="w-100" style="display:flex;justify-content:center;flex-direction: column;">
    <h3> Количество Постов - {{all_posts_count}} </h3> <br>
    <h3> Имеються контакты - {{with_contacts}} </h3>
</div>

{% for post in object_list %}


<div class="card mb-3 offset-md-2 col-md-9">
    <div class="row no-gutters">
      <div class="col-md-4">

          <!-- <img src="{{post.images.first.url}}" class="card-img post-img" alt="..." > -->
          <img src="{{post.preview}}" class="card-img post-img" alt="..." >

      </div>
      <div class="col-md-8">
        <div class="card-body">
          <a class="post-title" href="{% url 'main:post_details' post.id %}"><h6 class="card-title "> {{post.title}}</h6></a>
          <p class="card-text"> <span class="font-weight-bold">{{post.price}}</span>  <span class="post-price-cur">{{post.priceCurrency}}      </span>    {{post.pricePerMeter}}  <span style="padding-left: 20px;"></span> </p>
          <p class="card-text"> {{post.address}} </p>
          <!--<p class="card-text"><small class="text-muted">  post.description|truncatewords:25}}</small> </p>-->
          <p class="card-text"><small class="text-muted">{{post.contact_body | safe}}</small> </p>
          <p class="card-text"><small class="text-muted">{{post.offerId}}</small> </p>
        </div>
      </div>
    </div>
  </div>




<!-- <div class="card">
    <div class="row no-gutters">
        <div class="col-sm-12 col-md-4 col-lg-4 post-image" >
            <img class="card-img img-fluid w-100 h-100" style="object-fit: cover;" src="https://smartwebgate.com/wp-content/uploads/2021/10/AdobeStock_126016889.jpeg" alt="Suresh Dasari Card">
        </div>
        <div class="col-sm-7 col-md-7 col-lg-7">
            <div class="card-body">
                <h5 class="card-title">Suresh Dasari</h5>
                <p class="card-text">Suresh Dasari is a founder and technical lead developer in tutlane.</p>
                <a href="#" class="btn btn-primary">View Profile</a>
            </div>
        </div>
    </div>
</div>  -->



{% endfor %}











<div class='pagination justify-content-center' style="padding-bottom: 40px;">
  {% if page_obj.has_previous %}
    <a href='{% url "main:home" %}?page={{ page_obj.previous_page_number }}'>Previous </a>
  {% endif %}

  <span class='mx-4'>
    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
  </span>

  {% if page_obj.has_next %}
    <a href='{% url "main:home" %}?page={{ page_obj.next_page_number }}' > Next</a>
  {% endif %}
</div>



























<style>

    .owl-prev, .owl-next{
        transform: scale(2);
    }
    .item{
        padding: 0% !important;
    }

    .post-title{
      font-size: 17px;
      text-decoration: none;
    }
    .post-price-cur{
      font-size: 12px;
    }
    .post-img{
      /* height:250px; */
      max-height: 250px;
      object-fit: cover;
    }


    /* default styles here for older browsers.
   I tend to go for a 600px - 960px width max but using percentages
*/
@media only screen and (min-width: 960px) {
    /* styles for browsers larger than 960px; */
    .item{
        padding: 0 !important;
        height: 400px !important;
    }

}
@media only screen and (min-width: 1440px) {
    /* styles for browsers larger than 1440px; */
    .card-img{
        /* width: 300px;
        height: 225px;
        border-radius: 10px; */
    }
}


@media only screen and (min-width: 2000px) {
    /* for sumo sized (mac) screens */
}
@media only screen and (max-device-width: 480px) {
   /* styles for mobile browsers smaller than 480px; (iPhone) */
}


@media only screen and (device-width: 768px) {
   /* default iPad screens */
}


/* different techniques for iPad screening */
@media only screen and (min-device-width: 481px) and (max-device-width: 1024px) and (orientation:portrait) {
  /* For portrait layouts only */
  /* .item{
        padding: 0 !important;
        height: 300px !important;
    } */
    .post-image{
        width: 300px;
        height: 225px;
    }

}

@media only screen and (min-device-width: 481px) and (max-device-width: 1024px) and (orientation:landscape) {
  /* For landscape layouts only */
    .post-image{
        width: 300px;
        height: 225px;
    }
    body{
        background-color: red;
    }


}
</style>




{% endblock content %}

templates/postDetails.html
{% extends 'wrapper.html' %}




{% block content %}


<!-- <div class="splide">
  <div class="splide__track">
		<ul class="splide__list">
			<li class="splide__slide" style="width: 150px">Slide 01</li>
			<li class="splide__slide" style="width: 250px">Slide 02</li>
			<li class="splide__slide" style="width: 200px">Slide 03</li>
		</ul>
  </div>
</div> -->
<div class="container">

<section id="demos">
  <div class="row">
    <div class="large-12 columns">
      <div class="owl-carousel owl-theme">
        
        <!--  if object.imagesProp %} -->
          {% for image in object.get_images %}
            <img class="item post-image"  src="{{image}}" alt="" srcset="">
          {% endfor %}
  
       <!--  else %}
            <img class="item post-image"  src="{{object.preview}}" alt="" srcset="">
         endif %} -->
          
      </div>
      </div>
  </div>
</section>



  <h4> {{ object.title}}</h4>
          <p class="card-text"> <span class="font-weight-bold">{{object.price}}</span>  <span class="post-price-cur">{{object.priceCurrency}}      </span>    {{object.pricePerMeter}}  <span style="padding-left: 20px;"></span> </p>

  <p class="offerAddress">{{object.address}} </p>
  <p class="offerAddress">{{object.published}} </p>
  <a href="{{object.source}}">Оригинал</a>

  <br>
  <br>



    {{object.contact_body | safe}}
  {{object.body | safe}}
  <!-- {{object.description}} -->


</div>

















































<script>
  $(document).ready(function() {
    $('.owl-carousel').owlCarousel({
      margin: 10,
      loop: true,
      autoWidth: true,
      items: 4,
      nav:true,
    })
  })
</script>















<style>
  .post-image{
    width: auto;
    object-fit: cover !important;
  }
  .owl-prev, .owl-next{
      transform: scale(2);
  }
  .item{
      padding: 0% !important;
      /* border-color: white; */
      border: 1px solid white;
  }

  .row{
    margin-right: 0 !important;
    margin-left: 0 !important;
  }

  span{
    font-size: 1.1rem;
    color: black;
  }

  .contacts-header{
    font-size: 20px !important;
    font-weight: 600;
  }

  .contacts-pb, .link-primary{
    margin-left: 20px;
  }

  .description, .table-category, .contacts-pb, .contacts-header, .offerNear, .offerStatus{
    margin-top: 20px;
  }
  .owl-nav, .owl-dots { display: block !important; }

  .offerAddress{
    margin-left: 5px;
  }


  /* default styles here for older browsers.
 I tend to go for a 600px - 960px width max but using percentages
*/
@media only screen and (min-width: 960px) {
  /* styles for browsers larger than 960px; */
  .item{
      padding: 0 !important;
      height: 300px !important;
  }

}
@media only screen and (min-width: 1440px) {
  /* styles for browsers larger than 1440px; */
}
@media only screen and (min-width: 2000px) {
  /* for sumo sized (mac) screens */
}
@media only screen and (max-device-width: 480px) {
 /* styles for mobile browsers smaller than 480px; (iPhone) */
}
@media only screen and (device-width: 768px) {
 /* default iPad screens */
}
/* different techniques for iPad screening */
@media only screen and (min-device-width: 481px) and (max-device-width: 1024px) and (orientation:portrait) {
/* For portrait layouts only */
/* .item{
      padding: 0 !important;
      height: 300px !important;
  } */

}

@media only screen and (min-device-width: 481px) and (max-device-width: 1024px) and (orientation:landscape) {
/* For landscape layouts only */
.item{
      padding: 0 !important;
      height: 300px !important;
  }

}

.owl-item ,.active{
  margin: 0 !important;
}

</style>







{% endblock content %}

templates/some.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    









        <div class="row">
            <div class="col-md-6 col-lg-6 col-sm-12">

            </div>
            <div class="col-md-6 col-lg-6 col-sm-12">
                
            </div>
        </div>





















</body>
</html>

templates/wrapper.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    


        <!-- Link to the file hosted on your server, -->
    <!-- <link rel="stylesheet" href="{% static 'splide.min.css' %}">
    <link rel="stylesheet" href="{% static 'splide-core.min.css' %}">
 -->

    <!-- <linkrel="stylesheet"   href="https://cdn.jsdelivr.net/npm/@splidejs/splide@2.4.21/dist/css/splide.min.css"/> -->

    <!-- <link rel="stylesheet" href="../static/owl/assets/css/docs.theme.min.css"> -->
    <link rel="stylesheet" href="../static/owl/assets/owlcarousel/assets/owl.carousel.min.css">
    <link rel="stylesheet" href="../static/owl/assets/owlcarousel/assets/owl.theme.default.min.css">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    
    
    
    
    <script src="../static/owl/assets/vendors/jquery.min.js"></script>
    <script src="../static/owl/assets/owlcarousel/owl.carousel.js"></script>
    
    
    
    
    
    
    <title>Document</title>
</head>
<body>
    

  

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid col-md-8 col-lg-8">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
              </li>
            </ul>
            <form class="d-flex">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>








    <br><br>


      {% comment %} <div class="container"> {% endcomment %}
        {% comment %} <div class="row"> {% endcomment %}
        <!-- <div class="col-lg-10 offse row"> -->

            <!-- <div class="col-lg-10" id="main">  -->

                {% block content %}
    
                {% endblock content %}
                    
             <!-- </div>  -->


             <!-- <div class="col-lg-2 sidebar-links" id="sticky-sidebar"> 
                <div class="sticky-top">
                    <div class="nav flex-column">
                        <a href="#_" class="nav-link">Link</a>
                        <a href="#_" class="nav-link">Link</a>
                        <a href="#_" class="nav-link">Link</a>
                        <a href="#_" class="nav-link">Link</a>
                        <a href="#_" class="nav-link">Link</a>
                    </div>
                </div>
            </div>  -->



            <!-- </div>  -->
            {% comment %} </div>  {% endcomment %}
      {% comment %} </div> {% endcomment %}









<!-- 
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.3.1.min.js"></script>



    <script src="{% static 'splide.min.js' %}"></script>
    <script src="{% static 'splide.js' %}"></script>
    <script src="{% static 'app.js' %}"></script> -->




    <script src="../static/owl/assets/vendors/highlight.js"></script>
    <script src="../static/owl/assets/js/app.js"></script>

</body>
</html>